#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_FILE="$SCRIPT_DIR/vars.yml"

# ── helpers ──────────────────────────────────────────────────────────────────
prompt() {
  local label="$1" default="${2:-}" var
  if [[ -n "$default" ]]; then
    read -rp "$label [$default]: " var
    echo "${var:-$default}"
  else
    while true; do
      read -rp "$label: " var
      [[ -n "$var" ]] && break
      echo "  (required)" >&2
    done
    echo "$var"
  fi
}

prompt_secret() {
  local label="$1" var
  while true; do
    read -rsp "$label: " var; echo >&2
    [[ -n "$var" ]] && break
    echo "  (required)" >&2
  done
  echo "$var"
}

gen_secret() {
  openssl rand -base64 32
}

gen_app_keys() {
  echo "$(openssl rand -base64 32),$(openssl rand -base64 32)"
}

warn() { echo "  $*" >&2; }

# ── guard against overwrite ───────────────────────────────────────────────────
if [[ -f "$OUT_FILE" ]]; then
  read -rp "vars.yml already exists. Overwrite? [y/N] " confirm
  [[ "${confirm,,}" == "y" ]] || { echo "Aborted."; exit 0; }
fi

echo ""
echo "=== Strapi vars.yml generator ==="
echo ""

# ── deployment ────────────────────────────────────────────────────────────────
echo "-- Deployment --"
SITE_NAME=$(prompt "site_name (used as directory name)")
REPO_URL=$(prompt "repo_url")
BRANCH=$(prompt "branch" "main")
BACKEND_SUBDIR=$(prompt "backend_subdir (subdirectory containing docker-compose.yml)" "Backend")
echo ""

# ── domain & SSL ─────────────────────────────────────────────────────────────
echo "-- Domain & SSL --"
DOMAIN_NAME=$(prompt "domain_name (e.g. api.example.com)")
SSL_EMAIL=$(prompt "ssl_email (used for Let's Encrypt notifications)")
echo ""

# ── database ─────────────────────────────────────────────────────────────────
echo "-- Database --"
DB_NAME=$(prompt "db_name" "strapi")
DB_USERNAME=$(prompt "db_username" "strapi")
DB_PASSWORD=$(prompt_secret "db_password")
echo ""

# ── strapi secrets ────────────────────────────────────────────────────────────
echo "-- Strapi secrets --"
warn "Press Enter to auto-generate a secret, or type your own."
echo ""

read -rp "  strapi_app_keys [auto-generate]: " val
APP_KEYS="${val:-$(gen_app_keys)}"

read -rp "  strapi_api_token_salt [auto-generate]: " val
API_TOKEN_SALT="${val:-$(gen_secret)}"

read -rp "  strapi_admin_jwt_secret [auto-generate]: " val
ADMIN_JWT_SECRET="${val:-$(gen_secret)}"

read -rp "  strapi_transfer_token_salt [auto-generate]: " val
TRANSFER_TOKEN_SALT="${val:-$(gen_secret)}"

read -rp "  strapi_jwt_secret [auto-generate]: " val
JWT_SECRET="${val:-$(gen_secret)}"

read -rp "  strapi_encryption_key [auto-generate]: " val
ENCRYPTION_KEY="${val:-$(gen_secret)}"
echo ""

# ── write file ────────────────────────────────────────────────────────────────
cat > "$OUT_FILE" <<EOF
# Generated by generate-vars.sh — DO NOT COMMIT THIS FILE
# Add ansible/vars.yml to your .gitignore

# Deployment
site_name: "$SITE_NAME"
repo_url: "$REPO_URL"
branch: "$BRANCH"
backend_subdir: "$BACKEND_SUBDIR"

# Domain & SSL
domain_name: "$DOMAIN_NAME"
ssl_email: "$SSL_EMAIL"

# Database
db_name: "$DB_NAME"
db_username: "$DB_USERNAME"
db_password: "$DB_PASSWORD"

# Strapi secrets
strapi_app_keys: "$APP_KEYS"
strapi_api_token_salt: "$API_TOKEN_SALT"
strapi_admin_jwt_secret: "$ADMIN_JWT_SECRET"
strapi_transfer_token_salt: "$TRANSFER_TOKEN_SALT"
strapi_jwt_secret: "$JWT_SECRET"
strapi_encryption_key: "$ENCRYPTION_KEY"
EOF

chmod 600 "$OUT_FILE"

echo "Written to: $OUT_FILE"
echo ""
echo "Make sure your domain ($DOMAIN_NAME) has an A record pointing to your VPS before running."
echo ""
echo "Next step:"
echo "  ansible-playbook deploy.yml -i inventory.example -e @vars.yml \\"
echo "    -e \"ansible_host=<VPS_IP> ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa\""
