#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
VARS_FILE="$SCRIPT_DIR/vars.sh"
FRONTEND_DIR="$REPO_ROOT/Frontend"
WRANGLER_TOML="$FRONTEND_DIR/wrangler.toml"

# ── helpers ───────────────────────────────────────────────────────────────────
prompt() {
  local label="$1" default="${2:-}" var
  if [[ -n "$default" ]]; then
    read -rp "$label [$default]: " var
    echo "${var:-$default}"
  else
    while true; do
      read -rp "$label: " var
      [[ -n "$var" ]] && break
      echo "  (required)" >&2
    done
    echo "$var"
  fi
}

prompt_secret() {
  local label="$1" var
  while true; do
    read -rsp "$label: " var; echo >&2
    [[ -n "$var" ]] && break
    echo "  (required)" >&2
  done
  echo "$var"
}

confirm() {
  local label="$1" default="${2:-y}"
  read -rp "$label [${default^^}/n]: " ans
  [[ "${ans:-$default}" =~ ^[Yy]$ ]]
}

step() { echo ""; echo "── $* ──"; }
info() { echo "  $*"; }

# ── prerequisites ─────────────────────────────────────────────────────────────
step "Checking prerequisites"

if ! command -v node &>/dev/null; then
  echo "Error: node is not installed. Install Node.js >= 22 first." >&2
  exit 1
fi

if ! command -v npm &>/dev/null; then
  echo "Error: npm is not installed." >&2
  exit 1
fi

NODE_MAJOR=$(node -e "process.stdout.write(process.version.replace('v','').split('.')[0])")
if [[ "$NODE_MAJOR" -lt 20 ]]; then
  echo "Error: Node.js >= 20 required (found $(node -v))." >&2
  exit 1
fi
info "Node $(node -v)  npm $(npm -v)  OK"

if ! command -v wrangler &>/dev/null && ! npx --no wrangler --version &>/dev/null 2>&1; then
  if confirm "wrangler not found globally. Install it globally now?"; then
    npm install -g wrangler
  else
    info "wrangler will be run via npx during deploy."
  fi
fi

# ── guard against overwrite ───────────────────────────────────────────────────
if [[ -f "$VARS_FILE" ]]; then
  read -rp "vars.sh already exists. Overwrite? [y/N] " confirm_ow
  [[ "${confirm_ow,,}" == "y" ]] || { echo "Aborted."; exit 0; }
fi

echo ""
echo "=== Cloudflare Worker setup wizard ==="
echo "This will configure the Astro project in Frontend/ for Cloudflare Workers."
echo ""

# ── project config ────────────────────────────────────────────────────────────
step "Project config"
while true; do
  RAW_NAME=$(prompt "Worker name (lowercase, hyphens OK, e.g. my-client-site)")
  # Normalize: lowercase, replace spaces/underscores with hyphens, strip invalid chars
  CF_PROJECT_NAME=$(echo "$RAW_NAME" | tr '[:upper:]' '[:lower:]' | tr ' _' '-' | sed 's/[^a-z0-9-]//g')
  if [[ "$CF_PROJECT_NAME" =~ ^[a-z0-9][a-z0-9-]*[a-z0-9]$|^[a-z0-9]$ ]]; then
    [[ "$CF_PROJECT_NAME" != "$RAW_NAME" ]] && info "Normalized to: $CF_PROJECT_NAME"
    break
  fi
  echo "  Invalid name after normalization ('$CF_PROJECT_NAME'). Use letters, numbers, and hyphens." >&2
done
REPO_URL=$(prompt "GitHub repo URL (e.g. https://github.com/org/repo)")
BRANCH=$(prompt "Deploy branch" "main")
echo ""

# ── Cloudflare credentials ────────────────────────────────────────────────────
step "Cloudflare credentials"
info "Account ID: Cloudflare dashboard → right sidebar on any zone page"
CF_ACCOUNT_ID=$(prompt "Cloudflare Account ID")
echo ""
info "API Token: My Profile → API Tokens → Create Token"
info "Required permissions: Workers Scripts:Edit, Workers Routes:Edit, Account Settings:Read"
CF_API_TOKEN=$(prompt_secret "Cloudflare API Token")
echo ""

# ── application environment variables ─────────────────────────────────────────
step "Application environment"
info "These are passed to the Astro app at runtime."
echo ""
STRAPI_API_URL=$(prompt "Strapi API URL (e.g. https://api.yourdomain.com)")
STRAPI_API_TOKEN=$(prompt_secret "Strapi API Token (secret — stored as Worker secret, not in wrangler.toml)")
echo ""

# ── custom domain (optional) ──────────────────────────────────────────────────
step "Custom domain (optional)"
CUSTOM_DOMAIN=$(prompt "Custom domain for this Worker (leave blank to skip)" "")
echo ""

# ── write vars.sh ─────────────────────────────────────────────────────────────
cat > "$VARS_FILE" <<EOF
# Generated by setup-cloudflare.sh — DO NOT COMMIT THIS FILE

# Cloudflare credentials
CF_ACCOUNT_ID="$CF_ACCOUNT_ID"
CF_API_TOKEN="$CF_API_TOKEN"

# Project config
CF_PROJECT_NAME="$CF_PROJECT_NAME"

# Application environment
STRAPI_API_URL="$STRAPI_API_URL"
STRAPI_API_TOKEN="$STRAPI_API_TOKEN"
EOF
chmod 600 "$VARS_FILE"
info "Written: cloudflare/vars.sh"

# ── install @astrojs/cloudflare adapter ───────────────────────────────────────
step "Installing @astrojs/cloudflare adapter"
cd "$FRONTEND_DIR"

if grep -q '"@astrojs/cloudflare"' package.json 2>/dev/null; then
  info "@astrojs/cloudflare already in package.json — skipping install"
else
  npm install @astrojs/cloudflare@^13.0.0
  npm install --save-dev wrangler@^4.61.1
  info "Installed @astrojs/cloudflare and wrangler"
fi

# ── generate wrangler.toml ────────────────────────────────────────────────────
step "Generating Frontend/wrangler.toml"

COMPAT_DATE=$(date +%Y-%m-%d)

DOMAIN_BLOCK=""
if [[ -n "$CUSTOM_DOMAIN" ]]; then
  DOMAIN_BLOCK=$(cat <<TOML

[[routes]]
pattern = "$CUSTOM_DOMAIN"
custom_domain = true
TOML
)
fi

cat > "$WRANGLER_TOML" <<TOML
# Generated by cloudflare/setup-cloudflare.sh
# Commit this file — it contains no secrets.
# Secrets are managed via \`wrangler secret put\` (see cloudflare/deploy.sh).

name = "$CF_PROJECT_NAME"
compatibility_date = "$COMPAT_DATE"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[vars]
STRAPI_API_URL = "$STRAPI_API_URL"
$DOMAIN_BLOCK
TOML

info "Written: Frontend/wrangler.toml"

# ── push Worker secrets ───────────────────────────────────────────────────────
step "Pushing Worker secrets to Cloudflare"
info "Secrets are encrypted at rest and never visible after being set."

export CLOUDFLARE_API_TOKEN="$CF_API_TOKEN"
export CLOUDFLARE_ACCOUNT_ID="$CF_ACCOUNT_ID"

cd "$FRONTEND_DIR"

# Build first so the worker exists before we can push secrets
# (wrangler secret put requires the worker to exist on first run — deploy creates it)
if confirm "Build and do an initial deploy now? (required to push secrets on first run)"; then
  npm run build
  npx wrangler deploy
  echo "$STRAPI_API_TOKEN" | npx wrangler secret put STRAPI_API_TOKEN
  info "Secrets pushed."
else
  info "Skipped. Run cloudflare/deploy.sh to deploy and push secrets later."
fi

# ── GitHub Actions secrets instructions ───────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════════════"
echo "  GitHub Actions secrets — add these to your repo"
echo "  $REPO_URL/settings/secrets/actions"
echo "════════════════════════════════════════════════════════"
echo ""
echo "  Secret name              Value"
echo "  ─────────────────────    ─────────────────────────────"
echo "  CLOUDFLARE_API_TOKEN     $CF_API_TOKEN"
echo "  CLOUDFLARE_ACCOUNT_ID    $CF_ACCOUNT_ID"
echo "  STRAPI_API_TOKEN         (your Strapi token — set above)"
echo ""
echo "  The workflow file is already at:"
echo "  .github/workflows/deploy-frontend.yml"
echo ""
echo "  Push to $BRANCH to trigger a deployment."
echo "════════════════════════════════════════════════════════"
echo ""
echo "Next steps:"
echo "  1. Add the secrets above to GitHub"
echo "  2. git add Frontend/wrangler.toml Frontend/package.json Frontend/astro.config.mjs"
echo "  3. git commit -m 'chore: add Cloudflare Worker deployment'"
echo "  4. git push — GitHub Actions will build and deploy automatically"
echo ""
echo "To deploy manually at any time:"
echo "  bash infrastructure/deploy.sh"
